# Multi-timepoint assessments {#sec-backcasting}

When reporting temporal trends in category-based indicators for species it is very important that only genuine changes in categories are included.[@butchart2005] Genuine changes are category changes due to improvements or deterioration in conservation efforts, while non-genuine changes are those that occur due to taxonomic changes or improvements in data or knowledge of species. Knowledge and data on species are constantly improving, which means that non-genuine changes can obscure genuine trends in species indicators if they are not controlled for in indicator calculations.

In the plant protection level assessment, areas of continued knowledge improvement include species distributions, habitat preferences, abundance (population size and density estimates), detection of species' presence in protected areas, protected area maps, land cover data, and data on the density and distribution of alien invasive plants in protected areas. Genuine causes of change in protection level are limited to newly proclaimed or deproclaimed protected areas, changes in protected area effectiveness, and changes in species' populations inside existing protected areas (which alters the protected area's contribution to the species' conservation target).

With each assessment, most, if not all of these factors will change, and therefore it is not possible to compare for example an SPI value calculated in 2025 with an SPI calculated in 2018. The solution is to use a method known as 'back-casting'[@butchart2025], where protection level categories are retrospectively adjusted to previous points in time based on best available knowledge at the time of assessment. Therefore, for each assessment, a fresh time series of the SPI is calculated, so that non-genuine changes in protection level are controlled for, and only genuine changes are reflected in the indicator trends.

## Sources of non-genuine changes in protection level assessments

In the plant protection level assessment, the following sources of non-genuine changes have been identified, and are being held constant across time points included in each assessment:

1.  **Taxonomic classification** - with each assessment the sampled list's taxonomy is updated to reflect the latest species classification, but the same species list is used for each back-casted time point.

2.  **Species distributions** - this includes suitable habitat maps and occurrence data. For each assessment, occurrence records for all sampled species are updated to reflect the best available knowledge on species' distributions, and where necessary, suitable habitat maps (which are based on occurrence data) are updated. The same occurrence data and suitable habitat maps are used for each back-casted time point.

3.  **Species targets** - as described in @sec-targets, several factors feed into the setting of species conservation targets. A change in any of these factors (for example Red List status, density estimates, or the extent of suitable habitat) between assessments can result in a different target for a particular species. Therefore, for each assessment, all targets are recalculated, but this set of targets is applied across all back-casted time points.

4.  **Improvements in SAPAD** - SAPAD, which is maintained by the Department of Forestry, Fisheries and the Environment is the source of protected areas data for South Africa. This database is constantly improved, for example correcting declaration date errors, as well as spatial corrections of protected area extent. With each assessment, the latest version of SAPAD is obtained, and it is processed into a representative protected areas spatial layer for each time point in the assessment.

## Limitations of the back-casting method

The most significant limitation of the back-casting method is that it is unable to integrate genuine changes in species' abundance in protected areas over time, other than what can be inferred from changes in the extent of natural vegetation in protected areas captured in land cover time series. Some abundance changes are broadly reflected in Red List data - for example genuine changes in Red List status over time - but is not granular enough to apply at the level of individual protected areas. It is for example not possible to discern from population counts associated with occurrence records whether changes in numbers of individuals recorded over time are due to genuine increases or decline, or due to survey methods, time of year, or other environmental conditions that affect the detectability of individual plants.

For species that have declined to such an extent that based on its current population status or habitat extent, its conservation target cannot be met without habitat restoration and population recovery efforts (species in target categories 2, 3, and 6), trends in decline over time can only be inferred from habitat loss, but the assessment methods are less sensitive to changes in abundance due to pressures not related to habitat loss, such as poaching. Using land cover to infer decline means that the assessment also cannot detect increases in abundance over time in protected areas, other than through changes in Red List status. The back-casting methods could be improved by including genuine changes in Red List status when setting conservation targets, particularly positive changes due to species recovery.
